namespace :parse do
  GRAMMAR_DIR = File.expand_path('../grammars', __dir__)
  LEMON_GRAMMAR = File.join(GRAMMAR_DIR, 'lemon_grammar.y')
  LEMON_PARSER = File.join(GRAMMAR_DIR, 'lemon_parser.rb')

  desc "Compile lemon_grammar.y with Racc"
  task :compile do
    sh "racc -o #{LEMON_PARSER} #{LEMON_GRAMMAR}"
    puts "Compiled: #{LEMON_PARSER}"
  end

  desc "Generate parserb.y from SQLite's parse.y with empty actions"
  task generate: :compile do
    require_relative '../grammars/lemon_parser'

    source_path = File.expand_path('../../sqlite-c/src/parse.y', __dir__)
    output_path = File.join(GRAMMAR_DIR, 'parserb.y')

    unless File.exist?(source_path)
      abort "Source file not found: #{source_path}"
    end

    content = File.read(source_path)
    parser = LemonParser.new
    ast = parser.parse(content)

    output = generate_stripped_grammar(ast)
    File.write(output_path, output)

    puts "Generated: #{output_path}"
    puts "  Lines: #{output.lines.count}"
  end

  def generate_stripped_grammar(ast)
    header = <<~HEADER
      // parserb.y - SQLite grammar for Ruby parser generation
      //
      // This file is auto-generated from SQLite's parse.y
      // C actions have been stripped and will be replaced with Ruby actions
      //
      // Generated by: rake parse:generate
      //

    HEADER

    lines = [header]

    ast.each do |node|
      case node.first
      when :directive
        _, name, arg, _ = node
        if arg
          lines << "%#{name} #{arg}"
        else
          lines << "%#{name}"
        end

      when :directive_block
        _, name, _code = node
        lines << "// %#{name} block stripped (contained C code)"

      when :directive_typed
        _, name, ident, type = node
        lines << "%#{name} #{ident} {#{type}}"

      when :ifdef
        _, keyword, ident = node
        lines << "%#{keyword} #{ident}"

      when :endif
        if node.length > 1
          lines << "%endif #{node[1]}"
        else
          lines << "%endif"
        end

      when :rule
        _, lhs, rhs_list, action, precedence = node
        lhs_str = format_lhs(lhs)
        rhs_str = format_rhs(rhs_list)
        prec_str = precedence ? " [#{precedence}]" : ""
        if action
          lines << "#{lhs_str} ::= #{rhs_str}.#{prec_str} { # TODO rewrite in Ruby }"
        else
          lines << "#{lhs_str} ::= #{rhs_str}.#{prec_str}"
        end

      when :comment
        lines << node[1]
      end
    end

    lines.join("\n") + "\n"
  end

  def format_lhs(lhs)
    name, alias_name = lhs
    if alias_name
      "#{name}(#{alias_name})"
    else
      name
    end
  end

  def format_rhs(rhs_list)
    return "" if rhs_list.empty?

    rhs_list.map do |item|
      case item.first
      when :alt
        # item[1] is array of prefix identifiers, item[2] is [name, alias_or_nil]
        prefix = item[1].join('|')
        last_name, last_alias = item[2]
        last_part = last_alias ? "#{last_name}(#{last_alias})" : last_name
        "#{prefix}|#{last_part}"
      else
        name, alias_name = item
        if alias_name
          "#{name}(#{alias_name})"
        else
          name
        end
      end
    end.join(' ')
  end
end
