#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "lemon_grammar.y".
#

require 'racc/parser.rb'

require 'strscan'

class LemonParser < Racc::Parser

module_eval(<<'...end lemon_grammar.y/module_eval...', 'lemon_grammar.y', 77)
  LIST_DIRECTIVES = %w[token left right nonassoc token_class]
  BLOCK_DIRECTIVES = %w[include syntax_error stack_overflow parse_failure parse_accept]
  TYPE_DIRECTIVES = %w[type token_type default_type extra_context extra_argument]

  def parse(str)
    @tokens = tokenize(str)
    @pos = 0
    do_parse
  end

  def next_token
    @tokens[@pos].tap { @pos += 1 }
  end

  def tokenize(str)
    tokens = []
    s = StringScanner.new(str)

    until s.eos?
      case
      when s.scan(/\s+/)
        # skip whitespace
      when s.scan(%r{//[^\n]*})
        tokens << [:COMMENT, s.matched]
      when s.scan(%r{/\*.*?\*/}m)
        tokens << [:COMMENT, s.matched]
      when s.scan(/::=/)
        tokens << [:ASSIGN, '::=']
      when s.scan(/%/)
        tokens << [:PERCENT, '%']
      when s.scan(/\{/)
        content = read_balanced_braces(s)
        tokens << [:BRACED, content]
      when s.scan(/\(/)
        tokens << [:LPAREN, '(']
      when s.scan(/\)/)
        tokens << [:RPAREN, ')']
      when s.scan(/\[/)
        tokens << [:LBRACKET, '[']
      when s.scan(/\]/)
        tokens << [:RBRACKET, ']']
      when s.scan(/\./)
        tokens << [:DOT, '.']
      when s.scan(/\|\|/)
        tokens << [:DPIPE, '||']
      when s.scan(/&&/)
        tokens << [:DAMP, '&&']
      when s.scan(/!/)
        tokens << [:BANG, '!']
      when s.scan(/\|/)
        tokens << [:PIPE, '|']
      when s.scan(/0x[0-9a-fA-F]+|\d+/)
        tokens << [:NUMBER, s.matched]
      when s.scan(/[a-zA-Z_][a-zA-Z0-9_]*/)
        word = s.matched
        case word
        when 'ifdef', 'ifndef', 'if'
          tokens << [:IFDEF, word]
        when 'else'
          tokens << [:ELSE, word]
        when 'endif'
          tokens << [:ENDIF, word]
        when 'fallback'
          tokens << [:FALLBACK, word]
        when 'wildcard'
          tokens << [:WILDCARD, word]
        when 'destructor'
          tokens << [:DESTRUCTOR, word]
        when *LIST_DIRECTIVES
          tokens << [:LIST_DIR, word]
        when *BLOCK_DIRECTIVES
          tokens << [:BLOCK_DIR, word]
        when *TYPE_DIRECTIVES
          tokens << [:TYPE_DIR, word]
        else
          tokens << [:IDENT, word]
        end
      else
        s.getch
      end
    end

    tokens << [false, false]
    tokens
  end

  def read_balanced_braces(s)
    depth = 1
    content = +''
    until s.eos? || depth == 0
      if s.scan(/\{/)
        depth += 1
        content << '{'
      elsif s.scan(/\}/)
        depth -= 1
        content << '}' if depth > 0
      elsif s.scan(/"(?:[^"\\]|\\.)*"/)
        content << s.matched
      elsif s.scan(/'(?:[^'\\]|\\.)*'/)
        content << s.matched
      elsif s.scan(%r{//[^\n]*})
        content << s.matched
      elsif s.scan(%r{/\*.*?\*/}m)
        content << s.matched
      elsif s.scan(/[^{}"'\/]+/)
        content << s.matched
      elsif s.scan(/./)
        content << s.matched
      end
    end
    content
  end
...end lemon_grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    13,    37,    14,    19,    15,    16,    37,    17,    18,    37,
    37,    20,    21,    22,    38,    46,    47,    66,    42,    38,
    43,    69,    38,    38,    74,    46,    47,    44,    63,    67,
    43,    68,    33,     3,    68,     8,     9,    44,    34,    32,
    11,    55,    31,    59,    20,    21,    22,    52,    53,    12,
    23,    24,    26,    27,    28,    29,    30,    41,    26,    49,
    50,    51,    54,    61,    62,    70,    72,    73,    75,    76,
    77 ]

racc_action_check = [
     9,    20,     9,     9,     9,     9,    22,     9,     9,    52,
    53,     9,     9,     9,    20,    25,    25,    55,    25,    22,
    25,    59,    52,    53,    70,    48,    48,    25,    48,    55,
    48,    59,    19,     1,    70,     2,     2,    48,    19,    18,
     2,    40,    18,    40,    47,    47,    47,    35,    35,     3,
    10,    11,    13,    14,    15,    16,    17,    24,    27,    28,
    30,    32,    38,    41,    44,    60,    67,    68,    72,    73,
    75 ]

racc_action_pointer = [
   nil,    33,    33,    49,   nil,   nil,   nil,   nil,   nil,    -4,
    29,    27,   nil,    45,    46,    47,    45,    49,    32,    25,
    -6,   nil,    -1,   nil,    50,    13,   nil,    51,    54,   nil,
    50,   nil,    51,   nil,   nil,    29,   nil,   nil,    55,   nil,
    36,    38,   nil,   nil,    57,   nil,   nil,    29,    23,   nil,
   nil,   nil,     2,     3,   nil,     7,   nil,   nil,   nil,     7,
    58,   nil,   nil,   nil,   nil,   nil,   nil,    59,    60,   nil,
    10,   nil,    45,    44,   nil,    60,   nil,   nil ]

racc_action_default = [
    -2,   -47,    -1,   -47,    -3,    -4,    -5,    -6,    -7,   -47,
   -47,   -36,    78,   -47,   -47,   -47,   -47,   -47,   -47,   -15,
   -47,   -24,   -25,   -38,   -47,   -47,   -18,   -47,   -47,   -11,
   -47,   -13,   -47,   -16,   -17,   -23,   -27,   -30,   -47,   -26,
   -47,   -47,    -8,   -19,   -47,   -21,   -22,   -47,   -47,   -10,
   -12,   -14,   -47,   -47,   -31,   -32,   -39,   -40,   -41,   -42,
   -47,   -37,   -20,    -9,   -28,   -29,   -33,   -47,   -47,   -45,
   -42,   -44,   -47,   -47,   -46,   -34,   -43,   -35 ]

racc_goto_table = [
    36,    57,    39,    25,     1,     2,     4,     5,     6,     7,
    35,    10,    40,    56,    58,    60,   nil,    48,   nil,   nil,
   nil,    71,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    64,    65 ]

racc_goto_check = [
     9,    13,     9,     7,     1,     2,     3,     4,     5,     6,
     8,    10,    11,    12,    14,    15,   nil,     7,   nil,   nil,
   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     9,     9 ]

racc_goto_pointer = [
   nil,     4,     5,     4,     5,     6,     7,   -10,   -10,   -20,
     9,   -11,   -27,   -39,   -26,   -25 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    45,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 27, :_reduce_1,
  0, 28, :_reduce_2,
  2, 28, :_reduce_3,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 29, :_reduce_7,
  4, 30, :_reduce_8,
  5, 30, :_reduce_9,
  4, 30, :_reduce_10,
  3, 30, :_reduce_11,
  4, 30, :_reduce_12,
  3, 30, :_reduce_13,
  4, 30, :_reduce_14,
  2, 30, :_reduce_15,
  3, 30, :_reduce_16,
  3, 30, :_reduce_17,
  1, 33, :_reduce_18,
  2, 33, :_reduce_19,
  3, 33, :_reduce_20,
  2, 33, :_reduce_21,
  2, 33, :_reduce_22,
  3, 32, :_reduce_23,
  2, 32, :_reduce_24,
  2, 32, :_reduce_25,
  3, 32, :_reduce_26,
  1, 34, :_reduce_27,
  3, 34, :_reduce_28,
  3, 34, :_reduce_29,
  1, 35, :_reduce_30,
  2, 35, :_reduce_31,
  4, 31, :_reduce_32,
  5, 31, :_reduce_33,
  7, 31, :_reduce_34,
  8, 31, :_reduce_35,
  1, 36, :_reduce_36,
  4, 36, :_reduce_37,
  0, 37, :_reduce_38,
  2, 37, :_reduce_39,
  1, 38, :_reduce_40,
  1, 38, :_reduce_41,
  1, 39, :_reduce_42,
  4, 39, :_reduce_43,
  2, 40, :_reduce_44,
  2, 41, :_reduce_45,
  3, 41, :_reduce_46 ]

racc_reduce_n = 47

racc_shift_n = 78

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMENT => 2,
  :PERCENT => 3,
  :LIST_DIR => 4,
  :DOT => 5,
  :FALLBACK => 6,
  :IDENT => 7,
  :WILDCARD => 8,
  :BLOCK_DIR => 9,
  :BRACED => 10,
  :DESTRUCTOR => 11,
  :TYPE_DIR => 12,
  :NUMBER => 13,
  :PIPE => 14,
  :IFDEF => 15,
  :ELSE => 16,
  :ENDIF => 17,
  :DPIPE => 18,
  :DAMP => 19,
  :BANG => 20,
  :ASSIGN => 21,
  :LBRACKET => 22,
  :RBRACKET => 23,
  :LPAREN => 24,
  :RPAREN => 25 }

racc_nt_base = 26

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMENT",
  "PERCENT",
  "LIST_DIR",
  "DOT",
  "FALLBACK",
  "IDENT",
  "WILDCARD",
  "BLOCK_DIR",
  "BRACED",
  "DESTRUCTOR",
  "TYPE_DIR",
  "NUMBER",
  "PIPE",
  "IFDEF",
  "ELSE",
  "ENDIF",
  "DPIPE",
  "DAMP",
  "BANG",
  "ASSIGN",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "$start",
  "grammar",
  "items",
  "item",
  "directive",
  "rule",
  "conditional",
  "token_list",
  "cond_expr",
  "cond_term",
  "lhs",
  "rhs_list",
  "rhs_item",
  "simple_item",
  "alt_sequence",
  "alt_prefix" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'lemon_grammar.y', 2)
  def _reduce_1(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 4)
  def _reduce_2(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 5)
  def _reduce_3(val, _values, result)
     result = val[0] << val[1] if val[1]; result ||= val[0]
    result
  end
.,.,

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'lemon_grammar.y', 10)
  def _reduce_7(val, _values, result)
     result = [:comment, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 13)
  def _reduce_8(val, _values, result)
     result = [:directive_list, val[1], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 15)
  def _reduce_9(val, _values, result)
     result = [:fallback, val[2], val[3]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 16)
  def _reduce_10(val, _values, result)
     result = [:wildcard, val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 18)
  def _reduce_11(val, _values, result)
     result = [:directive_block, val[1], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 19)
  def _reduce_12(val, _values, result)
     result = [:destructor, val[2], val[3]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 21)
  def _reduce_13(val, _values, result)
     result = [:directive_typed, val[1], nil, val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 22)
  def _reduce_14(val, _values, result)
     result = [:directive_typed, val[1], val[2], val[3]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 24)
  def _reduce_15(val, _values, result)
     result = [:directive, val[1], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 25)
  def _reduce_16(val, _values, result)
     result = [:directive, val[1], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 26)
  def _reduce_17(val, _values, result)
     result = [:directive, val[1], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 28)
  def _reduce_18(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 29)
  def _reduce_19(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 30)
  def _reduce_20(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 31)
  def _reduce_21(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 32)
  def _reduce_22(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 34)
  def _reduce_23(val, _values, result)
     result = [:ifdef, val[1], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 35)
  def _reduce_24(val, _values, result)
     result = [:else]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 36)
  def _reduce_25(val, _values, result)
     result = [:endif]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 37)
  def _reduce_26(val, _values, result)
     result = [:endif, val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 39)
  def _reduce_27(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 40)
  def _reduce_28(val, _values, result)
     result = "#{val[0]} || #{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 41)
  def _reduce_29(val, _values, result)
     result = "#{val[0]} && #{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 43)
  def _reduce_30(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 44)
  def _reduce_31(val, _values, result)
     result = "!#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 46)
  def _reduce_32(val, _values, result)
     result = [:rule, val[0], val[2], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 47)
  def _reduce_33(val, _values, result)
     result = [:rule, val[0], val[2], val[4]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 49)
  def _reduce_34(val, _values, result)
     result = [:rule, val[0], val[2], nil, val[5]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 51)
  def _reduce_35(val, _values, result)
     result = [:rule, val[0], val[2], val[7], val[5]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 53)
  def _reduce_36(val, _values, result)
     result = [val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 54)
  def _reduce_37(val, _values, result)
     result = [val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 56)
  def _reduce_38(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 57)
  def _reduce_39(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 59)
  def _reduce_40(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 60)
  def _reduce_41(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 62)
  def _reduce_42(val, _values, result)
     result = [val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 63)
  def _reduce_43(val, _values, result)
     result = [val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 65)
  def _reduce_44(val, _values, result)
     result = [:alt, val[0], val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 67)
  def _reduce_45(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'lemon_grammar.y', 68)
  def _reduce_46(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class LemonParser
