// parserb.y - SQLite grammar for Ruby parser generation
//
// This file is auto-generated from SQLite's parse.y
// C actions have been stripped and will be replaced with Ruby actions
//
// Generated by: rake parse:generate
//


// %include block stripped (contained C code)
// Setup for the parser stack
%stack_size 50
// Initial stack size
%stack_size_limit parserStackSizeLimit
// Function returning max stack size
%realloc parserStackRealloc
// realloc() for the stack
%free parserStackFree
// free() for the stack
// All token codes are small integers with #defines that begin with "TK_"
%token_prefix TK_
// The type of the data attached to each token is Token.  This is also the
// default type for non-terminals.
//
%token_type  {Token}
%default_type  {Token}
// An extra argument to the constructor for the parser, which is available
// to all actions.
%extra_context  {Parse *pParse}
// This code runs whenever there is a syntax error
//
// %syntax_error block stripped (contained C code)
// %stack_overflow block stripped (contained C code)
// The name of the generated procedure that implements the parser
// is as follows:
%name sqlite3Parser
// The following text is included near the beginning of the C source
// code file that implements the parser.
//
// %include block stripped (contained C code)
// end %include
// Input is a single SQL command
input ::= cmdlist.
cmdlist ::= cmdlist ecmd.
cmdlist ::= ecmd.
ecmd ::= SEMI.
ecmd ::= cmdx SEMI.
%ifndef SQLITE_OMIT_EXPLAIN
ecmd ::= explain cmdx SEMI. { # TODO rewrite in Ruby }
explain ::= EXPLAIN. { # TODO rewrite in Ruby }
explain ::= EXPLAIN QUERY PLAN. { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_EXPLAIN
cmdx ::= cmd. { # TODO rewrite in Ruby }
///////////////////// Begin and end transactions. ////////////////////////////
//
cmd ::= BEGIN transtype(Y) trans_opt. { # TODO rewrite in Ruby }
trans_opt ::= .
trans_opt ::= TRANSACTION.
trans_opt ::= TRANSACTION nm.
%type transtype {int}
transtype(A) ::= . { # TODO rewrite in Ruby }
transtype(A) ::= DEFERRED(X). { # TODO rewrite in Ruby }
transtype(A) ::= IMMEDIATE(X). { # TODO rewrite in Ruby }
transtype(A) ::= EXCLUSIVE(X). { # TODO rewrite in Ruby }
cmd ::= COMMIT|END(X) trans_opt. { # TODO rewrite in Ruby }
cmd ::= ROLLBACK(X) trans_opt. { # TODO rewrite in Ruby }
savepoint_opt ::= SAVEPOINT.
savepoint_opt ::= .
cmd ::= SAVEPOINT nm(X). { # TODO rewrite in Ruby }
cmd ::= RELEASE savepoint_opt nm(X). { # TODO rewrite in Ruby }
cmd ::= ROLLBACK trans_opt TO savepoint_opt nm(X). { # TODO rewrite in Ruby }
///////////////////// The CREATE TABLE statement ////////////////////////////
//
cmd ::= create_table create_table_args.
create_table ::= createkw temp(T) TABLE ifnotexists(E) nm(Y) dbnm(Z). { # TODO rewrite in Ruby }
createkw(A) ::= CREATE(A). { # TODO rewrite in Ruby }
%type ifnotexists {int}
ifnotexists(A) ::= . { # TODO rewrite in Ruby }
ifnotexists(A) ::= IF NOT EXISTS. { # TODO rewrite in Ruby }
%type temp {int}
%ifndef SQLITE_OMIT_TEMPDB
temp(A) ::= TEMP. { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_TEMPDB
temp(A) ::= . { # TODO rewrite in Ruby }
create_table_args ::= LP columnlist conslist_opt(X) RP(E) table_option_set(F). { # TODO rewrite in Ruby }
create_table_args ::= AS select(S). { # TODO rewrite in Ruby }
%type table_option_set {u32}
%type table_option {u32}
table_option_set(A) ::= . { # TODO rewrite in Ruby }
table_option_set(A) ::= table_option(A).
table_option_set(A) ::= table_option_set(X) COMMA table_option(Y). { # TODO rewrite in Ruby }
table_option(A) ::= WITHOUT nm(X). { # TODO rewrite in Ruby }
table_option(A) ::= nm(X). { # TODO rewrite in Ruby }
columnlist ::= columnlist COMMA columnname carglist.
columnlist ::= columnname carglist.
columnname(A) ::= nm(A) typetoken(Y). { # TODO rewrite in Ruby }
// Declare some tokens early in order to influence their values, to 
// improve performance and reduce the executable size.  The goal here is
// to get the "jump" operations in ISNULL through ESCAPE to have numeric
// values that are early enough so that all jump operations are clustered
// at the beginning.  Also, operators like NE and EQ need to be adjacent,
// and all of the comparison operators need to be clustered together.
// Various assert() statements throughout the code enforce these restrictions.
//
// The following directive causes tokens ABORT, AFTER, ASC, etc. to
// fallback to ID if they will not parse as their original value.
// This obviates the need for the "id" nonterminal.
//
// Define operator precedence early so that this is the first occurrence
// of the operator tokens in the grammar.  Keeping the operators together
// causes them to be assigned integer values that are close together,
// which keeps parser tables smaller.
//
// The token values assigned to these symbols is determined by the order
// in which lemon first sees them.  It must be the case that ISNULL/NOTNULL,
// NE/EQ, GT/LE, and GE/LT are separated by only a single value.  See
// the sqlite3ExprIfFalse() routine for additional information on this
// constraint.
//
// An IDENTIFIER can be a generic identifier, or one of several
// keywords.  Any non-standard keyword can also be an identifier.
//
// And "ids" is an identifier-or-string.
//
// An identifier or a join-keyword
//
%type idj {Token}
idj(A) ::= ID(A).
idj(A) ::= JOIN_KW(A).

// An identifier or string
%type ids {Token}
ids(A) ::= ID(A).
ids(A) ::= STRING(A).

// The name of a column or table can be any of the following:
//
%type nm {Token}
nm(A) ::= idj(A).
nm(A) ::= STRING(A).
// A typetoken is really zero or more tokens that form a type name such
// as can be found after the column name in a CREATE TABLE statement.
// Multiple tokens are concatenated to form the value of the typetoken.
//
%type typetoken {Token}
typetoken(A) ::= . { # TODO rewrite in Ruby }
typetoken(A) ::= typename(A).
typetoken(A) ::= typename(A) LP signed RP(Y). { # TODO rewrite in Ruby }
typetoken(A) ::= typename(A) LP signed COMMA signed RP(Y). { # TODO rewrite in Ruby }
%type typename {Token}
typename(A) ::= ids(A).
typename(A) ::= typename(A) ids(Y). { # TODO rewrite in Ruby }
signed ::= plus_num.
signed ::= minus_num.
// The scanpt non-terminal takes a value which is a pointer to the
// input text just past the last token that has been shifted into
// the parser.  By surrounding some phrase in the grammar with two
// scanpt non-terminals, we can capture the input text for that phrase.
// For example:
//
//      something ::= .... scanpt(A) phrase scanpt(Z).
//
// The text that is parsed as "phrase" is a string starting at A
// and containing (int)(Z-A) characters.  There might be some extra
// whitespace on either end of the text, but that can be removed in
// post-processing, if needed.
//
%type scanpt {const char*}
scanpt(A) ::= . { nil }
scantok(A) ::= . { # TODO rewrite in Ruby }
// "carglist" is a list of additional constraints that come after the
// column name and column type in a CREATE TABLE statement.
//
carglist ::= carglist ccons.
carglist ::= .
ccons ::= CONSTRAINT nm(X). { # TODO rewrite in Ruby }
ccons ::= DEFAULT scantok(A) term(X). { # TODO rewrite in Ruby }
ccons ::= DEFAULT LP(A) expr(X) RP(Z). { # TODO rewrite in Ruby }
ccons ::= DEFAULT PLUS(A) scantok(Z) term(X). { # TODO rewrite in Ruby }
ccons ::= DEFAULT MINUS(A) scantok(Z) term(X). { # TODO rewrite in Ruby }
ccons ::= DEFAULT scantok id(X). { # TODO rewrite in Ruby }
// In addition to the type name, we also care about the primary key and
// UNIQUE constraints.
//
ccons ::= NULL onconf.
ccons ::= NOT NULL onconf(R). { # TODO rewrite in Ruby }
ccons ::= PRIMARY KEY sortorder(Z) onconf(R) autoinc(I). { # TODO rewrite in Ruby }
ccons ::= UNIQUE onconf(R). { # TODO rewrite in Ruby }
ccons ::= CHECK LP(A) expr(X) RP(B). { # TODO rewrite in Ruby }
ccons ::= REFERENCES nm(T) eidlist_opt(TA) refargs(R). { # TODO rewrite in Ruby }
ccons ::= defer_subclause(D). { # TODO rewrite in Ruby }
ccons ::= COLLATE ids(C). { # TODO rewrite in Ruby }
ccons ::= GENERATED ALWAYS AS generated.
ccons ::= AS generated.
generated ::= LP expr(E) RP. { # TODO rewrite in Ruby }
generated ::= LP expr(E) RP ID(TYPE). { # TODO rewrite in Ruby }
// The optional AUTOINCREMENT keyword
%type autoinc {int}
autoinc(X) ::= . { # TODO rewrite in Ruby }
autoinc(X) ::= AUTOINCR. { # TODO rewrite in Ruby }
// The next group of rules parses the arguments to a REFERENCES clause
// that determine if the referential integrity checking is deferred or
// or immediate and which determine what action to take if a ref-integ
// check fails.
//
%type refargs {int}
refargs(A) ::= . { # TODO rewrite in Ruby }
refargs(A) ::= refargs(A) refarg(Y). { # TODO rewrite in Ruby }
%type refarg {struct {int value; int mask;}}
refarg(A) ::= MATCH nm. { # TODO rewrite in Ruby }
refarg(A) ::= ON INSERT refact. { # TODO rewrite in Ruby }
refarg(A) ::= ON DELETE refact(X). { # TODO rewrite in Ruby }
refarg(A) ::= ON UPDATE refact(X). { # TODO rewrite in Ruby }
%type refact {int}
refact(A) ::= SET NULL. { # TODO rewrite in Ruby }
refact(A) ::= SET DEFAULT. { # TODO rewrite in Ruby }
refact(A) ::= CASCADE. { # TODO rewrite in Ruby }
refact(A) ::= RESTRICT. { # TODO rewrite in Ruby }
refact(A) ::= NO ACTION. { # TODO rewrite in Ruby }
%type defer_subclause {int}
defer_subclause(A) ::= NOT DEFERRABLE init_deferred_pred_opt. { # TODO rewrite in Ruby }
defer_subclause(A) ::= DEFERRABLE init_deferred_pred_opt(X). { # TODO rewrite in Ruby }
%type init_deferred_pred_opt {int}
init_deferred_pred_opt(A) ::= . { # TODO rewrite in Ruby }
init_deferred_pred_opt(A) ::= INITIALLY DEFERRED. { # TODO rewrite in Ruby }
init_deferred_pred_opt(A) ::= INITIALLY IMMEDIATE. { # TODO rewrite in Ruby }
conslist_opt(A) ::= . { # TODO rewrite in Ruby }
conslist_opt(A) ::= COMMA(A) conslist.
conslist ::= conslist tconscomma tcons.
conslist ::= tcons.
tconscomma ::= COMMA. { # TODO rewrite in Ruby }
tconscomma ::= .
tcons ::= CONSTRAINT nm(X). { # TODO rewrite in Ruby }
tcons ::= PRIMARY KEY LP sortlist(X) autoinc(I) RP onconf(R). { # TODO rewrite in Ruby }
tcons ::= UNIQUE LP sortlist(X) RP onconf(R). { # TODO rewrite in Ruby }
tcons ::= CHECK LP(A) expr(E) RP(B) onconf. { # TODO rewrite in Ruby }
tcons ::= FOREIGN KEY LP eidlist(FA) RP REFERENCES nm(T) eidlist_opt(TA) refargs(R) defer_subclause_opt(D). { # TODO rewrite in Ruby }
%type defer_subclause_opt {int}
defer_subclause_opt(A) ::= . { # TODO rewrite in Ruby }
defer_subclause_opt(A) ::= defer_subclause(A).
// The following is a non-standard extension that allows us to declare the
// default behavior when there is a constraint conflict.
//
%type onconf {int}
%type orconf {int}
%type resolvetype {int}
onconf(A) ::= . { # TODO rewrite in Ruby }
onconf(A) ::= ON CONFLICT resolvetype(X). { # TODO rewrite in Ruby }
orconf(A) ::= . { # TODO rewrite in Ruby }
orconf(A) ::= OR resolvetype(X). { # TODO rewrite in Ruby }
resolvetype(A) ::= raisetype(A).
resolvetype(A) ::= IGNORE. { # TODO rewrite in Ruby }
resolvetype(A) ::= REPLACE. { # TODO rewrite in Ruby }
////////////////////////// The DROP TABLE /////////////////////////////////////
//
cmd ::= DROP TABLE ifexists(E) fullname(X). { # TODO rewrite in Ruby }
%type ifexists {int}
ifexists(A) ::= IF EXISTS. { # TODO rewrite in Ruby }
ifexists(A) ::= . { # TODO rewrite in Ruby }
///////////////////// The CREATE VIEW statement /////////////////////////////
//
%ifndef SQLITE_OMIT_VIEW
cmd ::= createkw(X) temp(T) VIEW ifnotexists(E) nm(Y) dbnm(Z) eidlist_opt(C) AS select(S). { # TODO rewrite in Ruby }
cmd ::= DROP VIEW ifexists(E) fullname(X). { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_VIEW
//////////////////////// The SELECT statement /////////////////////////////////
//
cmd ::= select(X). { @prepare_context.finish_select }
%type select {Select*}
%type selectnowith {Select*}
%type oneselect {Select*}
// %include block stripped (contained C code)
%ifndef SQLITE_OMIT_CTE
select(A) ::= WITH wqlist(W) selectnowith(X). { # TODO rewrite in Ruby }
select(A) ::= WITH RECURSIVE wqlist(W) selectnowith(X). { # TODO rewrite in Ruby }
%endif
/* SQLITE_OMIT_CTE */
select(A) ::= selectnowith(A). { A }
selectnowith(A) ::= oneselect(A).
%ifndef SQLITE_OMIT_COMPOUND_SELECT
selectnowith(A) ::= selectnowith(A) multiselect_op(Y) oneselect(Z). { # TODO rewrite in Ruby }
%type multiselect_op {int}
multiselect_op(A) ::= UNION(OP). { # TODO rewrite in Ruby }
multiselect_op(A) ::= UNION ALL. { # TODO rewrite in Ruby }
multiselect_op(A) ::= EXCEPT|INTERSECT(OP). { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_COMPOUND_SELECT
oneselect(A) ::= SELECT distinct(D) selcollist(W) from(X) where_opt(Y) groupby_opt(P) having_opt(Q) orderby_opt(Z) limit_opt(L). { @prepare_context.build_select(W, X, Y) }
%ifndef SQLITE_OMIT_WINDOWFUNC
oneselect(A) ::= SELECT distinct(D) selcollist(W) from(X) where_opt(Y) groupby_opt(P) having_opt(Q) window_clause(R) orderby_opt(Z) limit_opt(L). { # TODO rewrite in Ruby }
%endif
// Single row VALUES clause.
//
%type values {Select*}
oneselect(A) ::= values(A).
values(A) ::= VALUES LP nexprlist(X) RP. { # TODO rewrite in Ruby }
// Multiple row VALUES clause.
//
%type mvalues {Select*}
oneselect(A) ::= mvalues(A). { # TODO rewrite in Ruby }
mvalues(A) ::= values(A) COMMA LP nexprlist(Y) RP. { # TODO rewrite in Ruby }
mvalues(A) ::= mvalues(A) COMMA LP nexprlist(Y) RP. { # TODO rewrite in Ruby }
// The "distinct" nonterminal is true (1) if the DISTINCT keyword is
// present and false (0) if it is not.
//
%type distinct {int}
distinct(A) ::= DISTINCT. { # TODO rewrite in Ruby }
distinct(A) ::= ALL. { # TODO rewrite in Ruby }
distinct(A) ::= . { nil }
// selcollist is a list of expressions that are to become the return
// values of the SELECT statement.  The "*" in statements like
// "SELECT * FROM ..." is encoded as a special expression with an
// opcode of TK_ASTERISK.
//
%type selcollist {ExprList*}
%type sclp {ExprList*}
sclp(A) ::= selcollist(A) COMMA.
sclp(A) ::= . { [] }
selcollist(A) ::= sclp(A) scanpt(B) expr(X) scanpt(Z) as(Y). { A << { expr: X, alias: Y }; A }
selcollist(A) ::= sclp(A) scanpt STAR(X). { A << { star: true }; A }
selcollist(A) ::= sclp(A) scanpt nm(X) DOT STAR(Y). { # TODO rewrite in Ruby }
// An option "AS <id>" phrase that can follow one of the expressions that
// define the result set, or one of the tables in the FROM clause.
//
%type as {Token}
as(X) ::= AS nm(Y). { Y.value }
as(X) ::= ids(X). { X.value }
as(X) ::= . { nil }
%type seltablist {SrcList*}
%type stl_prefix {SrcList*}
%type from {SrcList*}
// A complete FROM clause.
//
from(A) ::= . { nil }
from(A) ::= FROM seltablist(X). { X }
// "seltablist" is a "Select Table List" - the content of the FROM clause
// in a SELECT statement.  "stl_prefix" is a prefix of this list.
//
stl_prefix(A) ::= seltablist(A) joinop(Y). { A }
stl_prefix(A) ::= . { [] }
seltablist(A) ::= stl_prefix(A) nm(Y) dbnm(D) as(Z) on_using(N). { A << { table: Y.value, alias: Z }; A }
seltablist(A) ::= stl_prefix(A) nm(Y) dbnm(D) as(Z) indexed_by(I) on_using(N). { # TODO rewrite in Ruby }
seltablist(A) ::= stl_prefix(A) nm(Y) dbnm(D) LP exprlist(E) RP as(Z) on_using(N). { # TODO rewrite in Ruby }
%ifndef SQLITE_OMIT_SUBQUERY
seltablist(A) ::= stl_prefix(A) LP select(S) RP as(Z) on_using(N). { # TODO rewrite in Ruby }
seltablist(A) ::= stl_prefix(A) LP seltablist(F) RP as(Z) on_using(N). { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_SUBQUERY
%type dbnm {Token}
dbnm(A) ::= . { nil }
dbnm(A) ::= DOT nm(X). { # TODO rewrite in Ruby }
%type fullname {SrcList*}
fullname(A) ::= nm(X). { # TODO rewrite in Ruby }
fullname(A) ::= nm(X) DOT nm(Y). { # TODO rewrite in Ruby }
%type xfullname {SrcList*}
xfullname(A) ::= nm(X). { # TODO rewrite in Ruby }
xfullname(A) ::= nm(X) DOT nm(Y). { # TODO rewrite in Ruby }
xfullname(A) ::= nm(X) AS nm(Z). { # TODO rewrite in Ruby }
xfullname(A) ::= nm(X) DOT nm(Y) AS nm(Z). { # TODO rewrite in Ruby }
%type joinop {int}
joinop(X) ::= COMMA|JOIN. { # TODO rewrite in Ruby }
joinop(X) ::= JOIN_KW(A) JOIN. { # TODO rewrite in Ruby }
joinop(X) ::= JOIN_KW(A) nm(B) JOIN. { # TODO rewrite in Ruby }
joinop(X) ::= JOIN_KW(A) nm(B) nm(C) JOIN. { # TODO rewrite in Ruby }
// There is a parsing ambiguity in an upsert statement that uses a
// SELECT on the RHS of a the INSERT:
//
//      INSERT INTO tab SELECT * FROM aaa JOIN bbb ON CONFLICT ...
//                                        here ----^^
//
// When the ON token is encountered, the parser does not know if it is
// the beginning of an ON CONFLICT clause, or the beginning of an ON
// clause associated with the JOIN.  The conflict is resolved in favor
// of the JOIN.  If an ON CONFLICT clause is intended, insert a dummy
// WHERE clause in between, like this:
//
//      INSERT INTO tab SELECT * FROM aaa JOIN bbb WHERE true ON CONFLICT ...
//
// The [AND] and [OR] precedence marks in the rules for on_using cause the
// ON in this context to always be interpreted as belonging to the JOIN.
//
%type on_using {OnOrUsing}
//%destructor on_using {sqlite3ClearOnOrUsing(pParse->db, &$$);}
on_using(N) ::= ON expr(E). { # TODO rewrite in Ruby }
on_using(N) ::= USING LP idlist(L) RP. { # TODO rewrite in Ruby }
on_using(N) ::= . [OR] { nil }
// Note that this block abuses the Token type just a little. If there is
// no "INDEXED BY" clause, the returned token is empty (z==0 && n==0). If
// there is an INDEXED BY clause, then the token is populated as per normal,
// with z pointing to the token data and n containing the number of bytes
// in the token.
//
// If there is a "NOT INDEXED" clause, then (z==0 && n==1), which is 
// normally illegal. The sqlite3SrcListIndexedBy() function 
// recognizes and interprets this as a special case.
//
%type indexed_opt {Token}
%type indexed_by {Token}
indexed_opt(A) ::= . { # TODO rewrite in Ruby }
indexed_opt(A) ::= indexed_by(A).
indexed_by(A) ::= INDEXED BY nm(X). { # TODO rewrite in Ruby }
indexed_by(A) ::= NOT INDEXED. { # TODO rewrite in Ruby }
%type orderby_opt {ExprList*}
// the sortlist non-terminal stores a list of expression where each
// expression is optionally followed by ASC or DESC to indicate the
// sort order.
//
%type sortlist {ExprList*}
orderby_opt(A) ::= . { nil }
orderby_opt(A) ::= ORDER BY sortlist(X). { # TODO rewrite in Ruby }
sortlist(A) ::= sortlist(A) COMMA expr(Y) sortorder(Z) nulls(X). { # TODO rewrite in Ruby }
sortlist(A) ::= expr(Y) sortorder(Z) nulls(X). { # TODO rewrite in Ruby }
%type sortorder {int}
sortorder(A) ::= ASC. { # TODO rewrite in Ruby }
sortorder(A) ::= DESC. { # TODO rewrite in Ruby }
sortorder(A) ::= . { # TODO rewrite in Ruby }
%type nulls {int}
nulls(A) ::= NULLS FIRST. { # TODO rewrite in Ruby }
nulls(A) ::= NULLS LAST. { # TODO rewrite in Ruby }
nulls(A) ::= . { # TODO rewrite in Ruby }
%type groupby_opt {ExprList*}
groupby_opt(A) ::= . { nil }
groupby_opt(A) ::= GROUP BY nexprlist(X). { # TODO rewrite in Ruby }
%type having_opt {Expr*}
having_opt(A) ::= . { nil }
having_opt(A) ::= HAVING expr(X). { # TODO rewrite in Ruby }
%type limit_opt {Expr*}
// The destructor for limit_opt will never fire in the current grammar.
// The limit_opt non-terminal only occurs at the end of a single production
// rule for SELECT statements.  As soon as the rule that create the 
// limit_opt non-terminal reduces, the SELECT statement rule will also
// reduce.  So there is never a limit_opt non-terminal on the stack 
// except as a transient.  So there is never anything to destroy.
//
//%destructor limit_opt {sqlite3ExprDelete(pParse->db, $$);}
limit_opt(A) ::= . { nil }
limit_opt(A) ::= LIMIT expr(X). { # TODO rewrite in Ruby }
limit_opt(A) ::= LIMIT expr(X) OFFSET expr(Y). { # TODO rewrite in Ruby }
limit_opt(A) ::= LIMIT expr(X) COMMA expr(Y). { # TODO rewrite in Ruby }
/////////////////////////// The DELETE statement /////////////////////////////
//
%if SQLITE_ENABLE_UPDATE_DELETE_LIMIT || SQLITE_UDL_CAPABLE_PARSER
cmd ::= with DELETE FROM xfullname(X) indexed_opt(I) where_opt_ret(W) orderby_opt(O) limit_opt(L). { # TODO rewrite in Ruby }
cmd ::= with DELETE FROM xfullname(X) indexed_opt(I) where_opt_ret(W). { # TODO rewrite in Ruby }
%endif
%type where_opt {Expr*}
%type where_opt_ret {Expr*}
where_opt(A) ::= . { nil }
where_opt(A) ::= WHERE expr(X). { X }
where_opt_ret(A) ::= . { # TODO rewrite in Ruby }
where_opt_ret(A) ::= WHERE expr(X). { # TODO rewrite in Ruby }
where_opt_ret(A) ::= RETURNING selcollist(X). { # TODO rewrite in Ruby }
where_opt_ret(A) ::= WHERE expr(X) RETURNING selcollist(Y). { # TODO rewrite in Ruby }
////////////////////////// The UPDATE command ////////////////////////////////
//
%if SQLITE_ENABLE_UPDATE_DELETE_LIMIT || SQLITE_UDL_CAPABLE_PARSER
cmd ::= with UPDATE orconf(R) xfullname(X) indexed_opt(I) SET setlist(Y) from(F) where_opt_ret(W) orderby_opt(O) limit_opt(L). { # TODO rewrite in Ruby }
cmd ::= with UPDATE orconf(R) xfullname(X) indexed_opt(I) SET setlist(Y) from(F) where_opt_ret(W). { # TODO rewrite in Ruby }
%endif
%type setlist {ExprList*}
setlist(A) ::= setlist(A) COMMA nm(X) EQ expr(Y). { # TODO rewrite in Ruby }
setlist(A) ::= setlist(A) COMMA LP idlist(X) RP EQ expr(Y). { # TODO rewrite in Ruby }
setlist(A) ::= nm(X) EQ expr(Y). { # TODO rewrite in Ruby }
setlist(A) ::= LP idlist(X) RP EQ expr(Y). { # TODO rewrite in Ruby }
////////////////////////// The INSERT command /////////////////////////////////
//
cmd ::= with insert_cmd(R) INTO xfullname(X) idlist_opt(F) select(S) upsert(U). { # TODO rewrite in Ruby }
cmd ::= with insert_cmd(R) INTO xfullname(X) idlist_opt(F) DEFAULT VALUES returning. { # TODO rewrite in Ruby }
%type upsert {Upsert*}
// Because upsert only occurs at the tip end of the INSERT rule for cmd,
// there is never a case where the value of the upsert pointer will not
// be destroyed by the cmd action.  So comment-out the destructor to
// avoid unreachable code.
//%destructor upsert {sqlite3UpsertDelete(pParse->db,$$);}
upsert(A) ::= . { # TODO rewrite in Ruby }
upsert(A) ::= RETURNING selcollist(X). { # TODO rewrite in Ruby }
upsert(A) ::= ON CONFLICT LP sortlist(T) RP where_opt(TW) DO UPDATE SET setlist(Z) where_opt(W) upsert(N). { # TODO rewrite in Ruby }
upsert(A) ::= ON CONFLICT LP sortlist(T) RP where_opt(TW) DO NOTHING upsert(N). { # TODO rewrite in Ruby }
upsert(A) ::= ON CONFLICT DO NOTHING returning. { # TODO rewrite in Ruby }
upsert(A) ::= ON CONFLICT DO UPDATE SET setlist(Z) where_opt(W) returning. { # TODO rewrite in Ruby }
returning ::= RETURNING selcollist(X). { # TODO rewrite in Ruby }
returning ::= .
%type insert_cmd {int}
insert_cmd(A) ::= INSERT orconf(R). { # TODO rewrite in Ruby }
insert_cmd(A) ::= REPLACE. { # TODO rewrite in Ruby }
%type idlist_opt {IdList*}
%type idlist {IdList*}
idlist_opt(A) ::= . { # TODO rewrite in Ruby }
idlist_opt(A) ::= LP idlist(X) RP. { # TODO rewrite in Ruby }
idlist(A) ::= idlist(A) COMMA nm(Y). { # TODO rewrite in Ruby }
idlist(A) ::= nm(Y). { # TODO rewrite in Ruby }
/////////////////////////// Expression Processing /////////////////////////////
//
%type expr {Expr*}
%type term {Expr*}
// %include block stripped (contained C code)
expr(A) ::= term(A).
expr(A) ::= LP expr(X) RP. { # TODO rewrite in Ruby }
expr(A) ::= idj(X). { @prepare_context.make_column_ref(X.value) }
expr(A) ::= nm(X) DOT nm(Y). { # TODO rewrite in Ruby }
expr(A) ::= nm(X) DOT nm(Y) DOT nm(Z). { # TODO rewrite in Ruby }
term(A) ::= NULL|FLOAT|BLOB(X). { # TODO rewrite in Ruby }
term(A) ::= STRING(X). { @prepare_context.make_string_literal(X.value) }
term(A) ::= INTEGER(X). { @prepare_context.make_integer_literal(X.value) }
expr(A) ::= VARIABLE(X). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) COLLATE ids(C). { # TODO rewrite in Ruby }
%ifndef SQLITE_OMIT_CAST
expr(A) ::= CAST LP expr(E) AS typetoken(T) RP. { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_CAST
expr(A) ::= idj(X) LP distinct(D) exprlist(Y) RP. { # TODO rewrite in Ruby }
expr(A) ::= idj(X) LP distinct(D) exprlist(Y) ORDER BY sortlist(O) RP. { # TODO rewrite in Ruby }
expr(A) ::= idj(X) LP STAR RP. { # TODO rewrite in Ruby }
%ifdef SQLITE_ENABLE_ORDERED_SET_AGGREGATES
// %include block stripped (contained C code)
expr(A) ::= idj(X) LP distinct(D) exprlist(Y) RP WITHIN GROUP LP ORDER BY expr(E) RP. { # TODO rewrite in Ruby }
%endif SQLITE_ENABLE_ORDERED_SET_AGGREGATES
%ifndef SQLITE_OMIT_WINDOWFUNC
expr(A) ::= idj(X) LP distinct(D) exprlist(Y) RP filter_over(Z). { # TODO rewrite in Ruby }
expr(A) ::= idj(X) LP distinct(D) exprlist(Y) ORDER BY sortlist(O) RP filter_over(Z). { # TODO rewrite in Ruby }
expr(A) ::= idj(X) LP STAR RP filter_over(Z). { # TODO rewrite in Ruby }
%ifdef SQLITE_ENABLE_ORDERED_SET_AGGREGATES
expr(A) ::= idj(X) LP distinct(D) exprlist(Y) RP WITHIN GROUP LP ORDER BY expr(E) RP filter_over(Z). { # TODO rewrite in Ruby }
%endif SQLITE_ENABLE_ORDERED_SET_AGGREGATES
%endif SQLITE_OMIT_WINDOWFUNC
term(A) ::= CTIME_KW(OP). { # TODO rewrite in Ruby }
expr(A) ::= LP nexprlist(X) COMMA expr(Y) RP. { # TODO rewrite in Ruby }
expr(A) ::= expr(A) AND expr(Y). { @prepare_context.make_and_expr(A, Y) }
expr(A) ::= expr(A) OR(OP) expr(Y). { @prepare_context.make_or_expr(A, Y) }
expr(A) ::= expr(A) LT|GT|GE|LE(OP) expr(Y). { @prepare_context.make_binary_expr(A, OP.value, Y) }
expr(A) ::= expr(A) EQ|NE(OP) expr(Y). { @prepare_context.make_binary_expr(A, OP.value == '!=' || OP.type == SqlitePurerb::Parserb::TK::NE ? '!=' : '=', Y) }
expr(A) ::= expr(A) BITAND|BITOR|LSHIFT|RSHIFT(OP) expr(Y). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) PLUS|MINUS(OP) expr(Y). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) STAR|SLASH|REM(OP) expr(Y). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) CONCAT(OP) expr(Y). { # TODO rewrite in Ruby }
%type likeop {Token}
likeop(A) ::= LIKE_KW|MATCH(A).
likeop(A) ::= NOT LIKE_KW|MATCH(X). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) likeop(OP) expr(Y). [LIKE_KW] { # TODO rewrite in Ruby }
expr(A) ::= expr(A) likeop(OP) expr(Y) ESCAPE expr(E). [LIKE_KW] { # TODO rewrite in Ruby }
// %include block stripped (contained C code)
expr(A) ::= expr(A) ISNULL|NOTNULL(E). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) NOT NULL. { # TODO rewrite in Ruby }
//    expr1 IS expr2       same as    expr1 IS NOT DISTICT FROM expr2
//    expr1 IS NOT expr2   same as    expr1 IS DISTINCT FROM expr2
//
expr(A) ::= expr(A) IS expr(Y). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) IS NOT expr(Y). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) IS NOT DISTINCT FROM expr(Y). { # TODO rewrite in Ruby }
expr(A) ::= expr(A) IS DISTINCT FROM expr(Y). { # TODO rewrite in Ruby }
expr(A) ::= NOT(B) expr(X). { # TODO rewrite in Ruby }
expr(A) ::= BITNOT(B) expr(X). { # TODO rewrite in Ruby }
expr(A) ::= PLUS|MINUS(B) expr(X). [BITNOT] { # TODO rewrite in Ruby }
expr(A) ::= expr(B) PTR(C) expr(D). { # TODO rewrite in Ruby }
%type between_op {int}
between_op(A) ::= BETWEEN. { # TODO rewrite in Ruby }
between_op(A) ::= NOT BETWEEN. { # TODO rewrite in Ruby }
expr(A) ::= expr(A) between_op(N) expr(X) AND expr(Y). [BETWEEN] { # TODO rewrite in Ruby }
%ifndef SQLITE_OMIT_SUBQUERY
%type in_op {int}
in_op(A) ::= IN. { # TODO rewrite in Ruby }
in_op(A) ::= NOT IN. { # TODO rewrite in Ruby }
expr(A) ::= expr(A) in_op(N) LP exprlist(Y) RP. [IN] { # TODO rewrite in Ruby }
expr(A) ::= LP select(X) RP. { # TODO rewrite in Ruby }
expr(A) ::= expr(A) in_op(N) LP select(Y) RP. [IN] { # TODO rewrite in Ruby }
expr(A) ::= expr(A) in_op(N) nm(Y) dbnm(Z) paren_exprlist(E). [IN] { # TODO rewrite in Ruby }
expr(A) ::= EXISTS LP select(Y) RP. { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_SUBQUERY
/* CASE expressions */
expr(A) ::= CASE case_operand(X) case_exprlist(Y) case_else(Z) END. { # TODO rewrite in Ruby }
%type case_exprlist {ExprList*}
case_exprlist(A) ::= case_exprlist(A) WHEN expr(Y) THEN expr(Z). { # TODO rewrite in Ruby }
case_exprlist(A) ::= WHEN expr(Y) THEN expr(Z). { # TODO rewrite in Ruby }
%type case_else {Expr*}
case_else(A) ::= ELSE expr(X). { # TODO rewrite in Ruby }
case_else(A) ::= . { # TODO rewrite in Ruby }
%type case_operand {Expr*}
case_operand(A) ::= expr(A).
case_operand(A) ::= . { # TODO rewrite in Ruby }
%type exprlist {ExprList*}
%type nexprlist {ExprList*}
exprlist(A) ::= nexprlist(A).
exprlist(A) ::= . { # TODO rewrite in Ruby }
nexprlist(A) ::= nexprlist(A) COMMA expr(Y). { # TODO rewrite in Ruby }
nexprlist(A) ::= expr(Y). { # TODO rewrite in Ruby }
%ifndef SQLITE_OMIT_SUBQUERY
/* A paren_exprlist is an optional expression list contained inside
** of parenthesis */
%type paren_exprlist {ExprList*}
paren_exprlist(A) ::= . { # TODO rewrite in Ruby }
paren_exprlist(A) ::= LP exprlist(X) RP. { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_SUBQUERY
///////////////////////////// The CREATE INDEX command ///////////////////////
//
cmd ::= createkw(S) uniqueflag(U) INDEX ifnotexists(NE) nm(X) dbnm(D) ON nm(Y) LP sortlist(Z) RP where_opt(W). { # TODO rewrite in Ruby }
%type uniqueflag {int}
uniqueflag(A) ::= UNIQUE. { # TODO rewrite in Ruby }
uniqueflag(A) ::= . { # TODO rewrite in Ruby }
// The eidlist non-terminal (Expression Id List) generates an ExprList
// from a list of identifiers.  The identifier names are in ExprList.a[].zName.
// This list is stored in an ExprList rather than an IdList so that it
// can be easily sent to sqlite3ColumnsExprList().
//
// eidlist is grouped with CREATE INDEX because it used to be the non-terminal
// used for the arguments to an index.  That is just an historical accident.
//
// IMPORTANT COMPATIBILITY NOTE:  Some prior versions of SQLite accepted
// COLLATE clauses and ASC or DESC keywords on ID lists in inappropriate
// places - places that might have been stored in the sqlite_schema table.
// Those extra features were ignored.  But because they might be in some
// (busted) old databases, we need to continue parsing them when loading
// historical schemas.
//
%type eidlist {ExprList*}
%type eidlist_opt {ExprList*}
// %include block stripped (contained C code)
// end %include
eidlist_opt(A) ::= . { # TODO rewrite in Ruby }
eidlist_opt(A) ::= LP eidlist(X) RP. { # TODO rewrite in Ruby }
eidlist(A) ::= eidlist(A) COMMA nm(Y) collate(C) sortorder(Z). { # TODO rewrite in Ruby }
eidlist(A) ::= nm(Y) collate(C) sortorder(Z). { # TODO rewrite in Ruby }
%type collate {int}
collate(C) ::= . { # TODO rewrite in Ruby }
collate(C) ::= COLLATE ids. { # TODO rewrite in Ruby }
///////////////////////////// The DROP INDEX command /////////////////////////
//
cmd ::= DROP INDEX ifexists(E) fullname(X). { # TODO rewrite in Ruby }
///////////////////////////// The VACUUM command /////////////////////////////
//
%if !SQLITE_OMIT_VACUUM && !SQLITE_OMIT_ATTACH
%type vinto {Expr*}
cmd ::= VACUUM vinto(Y). { # TODO rewrite in Ruby }
cmd ::= VACUUM nm(X) vinto(Y). { # TODO rewrite in Ruby }
vinto(A) ::= INTO expr(X). { # TODO rewrite in Ruby }
vinto(A) ::= . { # TODO rewrite in Ruby }
%endif
///////////////////////////// The PRAGMA command /////////////////////////////
//
%ifndef SQLITE_OMIT_PRAGMA
cmd ::= PRAGMA nm(X) dbnm(Z). { # TODO rewrite in Ruby }
cmd ::= PRAGMA nm(X) dbnm(Z) EQ nmnum(Y). { # TODO rewrite in Ruby }
cmd ::= PRAGMA nm(X) dbnm(Z) LP nmnum(Y) RP. { # TODO rewrite in Ruby }
cmd ::= PRAGMA nm(X) dbnm(Z) EQ minus_num(Y). { # TODO rewrite in Ruby }
cmd ::= PRAGMA nm(X) dbnm(Z) LP minus_num(Y) RP. { # TODO rewrite in Ruby }
nmnum(A) ::= plus_num(A).
nmnum(A) ::= nm(A).
nmnum(A) ::= ON(A).
nmnum(A) ::= DELETE(A).
nmnum(A) ::= DEFAULT(A).
%endif SQLITE_OMIT_PRAGMA
plus_num(A) ::= PLUS number(X). { # TODO rewrite in Ruby }
plus_num(A) ::= number(A).
minus_num(A) ::= MINUS number(X). { # TODO rewrite in Ruby }
//////////////////////////// The CREATE TRIGGER command /////////////////////
%ifndef SQLITE_OMIT_TRIGGER
cmd ::= createkw trigger_decl(A) BEGIN trigger_cmd_list(S) END(Z). { # TODO rewrite in Ruby }
trigger_decl(A) ::= temp(T) TRIGGER ifnotexists(NOERR) nm(B) dbnm(Z) trigger_time(C) trigger_event(D) ON fullname(E) foreach_clause when_clause(G). { # TODO rewrite in Ruby }
%type trigger_time {int}
trigger_time(A) ::= BEFORE|AFTER(X). { # TODO rewrite in Ruby }
trigger_time(A) ::= INSTEAD OF. { # TODO rewrite in Ruby }
trigger_time(A) ::= . { # TODO rewrite in Ruby }
%type trigger_event {struct TrigEvent}
trigger_event(A) ::= DELETE|INSERT(X). { # TODO rewrite in Ruby }
trigger_event(A) ::= UPDATE(X). { # TODO rewrite in Ruby }
trigger_event(A) ::= UPDATE OF idlist(X). { # TODO rewrite in Ruby }
foreach_clause ::= .
foreach_clause ::= FOR EACH ROW.
%type when_clause {Expr*}
when_clause(A) ::= . { # TODO rewrite in Ruby }
when_clause(A) ::= WHEN expr(X). { # TODO rewrite in Ruby }
%type trigger_cmd_list {TriggerStep*}
trigger_cmd_list(A) ::= trigger_cmd_list(A) trigger_cmd(X) SEMI. { # TODO rewrite in Ruby }
trigger_cmd_list(A) ::= trigger_cmd(A) SEMI. { # TODO rewrite in Ruby }
// Disallow the INDEX BY and NOT INDEXED clauses on UPDATE and DELETE
// statements within triggers.  We make a specific error message for this
// since it is an exception to the default grammar rules.
//
tridxby ::= .
tridxby ::= INDEXED BY nm. { # TODO rewrite in Ruby }
tridxby ::= NOT INDEXED. { # TODO rewrite in Ruby }
%type trigger_cmd {TriggerStep*}
// UPDATE 
trigger_cmd(A) ::= UPDATE(B) orconf(R) xfullname(X) tridxby SET setlist(Y) from(F) where_opt(Z) scanpt(E). { # TODO rewrite in Ruby }
// INSERT
trigger_cmd(A) ::= scanpt(B) insert_cmd(R) INTO xfullname(X) idlist_opt(F) select(S) upsert(U) scanpt(Z). { # TODO rewrite in Ruby }
// DELETE
trigger_cmd(A) ::= DELETE(B) FROM xfullname(X) tridxby where_opt(Y) scanpt(E). { # TODO rewrite in Ruby }
// SELECT
trigger_cmd(A) ::= scanpt(B) select(X) scanpt(E). { # TODO rewrite in Ruby }
// The special RAISE expression that may occur in trigger programs
expr(A) ::= RAISE LP IGNORE RP. { # TODO rewrite in Ruby }
expr(A) ::= RAISE LP raisetype(T) COMMA expr(Z) RP. { # TODO rewrite in Ruby }
%endif !SQLITE_OMIT_TRIGGER
%type raisetype {int}
raisetype(A) ::= ROLLBACK. { # TODO rewrite in Ruby }
raisetype(A) ::= ABORT. { # TODO rewrite in Ruby }
raisetype(A) ::= FAIL. { # TODO rewrite in Ruby }
////////////////////////  DROP TRIGGER statement //////////////////////////////
%ifndef SQLITE_OMIT_TRIGGER
cmd ::= DROP TRIGGER ifexists(NOERR) fullname(X). { # TODO rewrite in Ruby }
%endif !SQLITE_OMIT_TRIGGER
//////////////////////// ATTACH DATABASE file AS name /////////////////////////
%ifndef SQLITE_OMIT_ATTACH
cmd ::= ATTACH database_kw_opt expr(F) AS expr(D) key_opt(K). { # TODO rewrite in Ruby }
cmd ::= DETACH database_kw_opt expr(D). { # TODO rewrite in Ruby }
%type key_opt {Expr*}
key_opt(A) ::= . { # TODO rewrite in Ruby }
key_opt(A) ::= KEY expr(X). { # TODO rewrite in Ruby }
database_kw_opt ::= DATABASE.
database_kw_opt ::= .
%endif SQLITE_OMIT_ATTACH
////////////////////////// REINDEX collation //////////////////////////////////
%ifndef SQLITE_OMIT_REINDEX
cmd ::= REINDEX. { # TODO rewrite in Ruby }
cmd ::= REINDEX nm(X) dbnm(Y). { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_REINDEX
/////////////////////////////////// ANALYZE ///////////////////////////////////
%ifndef SQLITE_OMIT_ANALYZE
cmd ::= ANALYZE. { # TODO rewrite in Ruby }
cmd ::= ANALYZE nm(X) dbnm(Y). { # TODO rewrite in Ruby }
%endif
//////////////////////// ALTER TABLE table ... ////////////////////////////////
%ifndef SQLITE_OMIT_ALTERTABLE
%ifndef SQLITE_OMIT_VIRTUALTABLE
cmd ::= ALTER TABLE fullname(X) RENAME TO nm(Z). { # TODO rewrite in Ruby }
// The ALTER TABLE ADD COLUMN command. This is broken into two sections so
// that sqlite3AlterBeginAddColumn() is called before parsing the various
// constraints and so on (carglist) attached to the new column definition.
cmd ::= alter_add(Y) carglist. { # TODO rewrite in Ruby }
alter_add(A) ::= ALTER TABLE fullname(X) ADD kwcolumn_opt nm(Y) typetoken(Z). { # TODO rewrite in Ruby }
cmd ::= ALTER TABLE fullname(X) DROP kwcolumn_opt nm(Y). { # TODO rewrite in Ruby }
cmd ::= ALTER TABLE fullname(X) RENAME kwcolumn_opt nm(Y) TO nm(Z). { # TODO rewrite in Ruby }
cmd ::= ALTER TABLE fullname(X) DROP CONSTRAINT nm(Y). { # TODO rewrite in Ruby }
cmd ::= ALTER TABLE fullname(X) ALTER kwcolumn_opt nm(Y) DROP NOT NULL. { # TODO rewrite in Ruby }
cmd ::= ALTER TABLE fullname(X) ALTER kwcolumn_opt nm(Y) SET NOT(Z) NULL onconf. { # TODO rewrite in Ruby }
cmd ::= ALTER TABLE fullname(X) ADD CONSTRAINT(Y) nm(Z) CHECK LP(A) expr RP(B) onconf. { # TODO rewrite in Ruby }
cmd ::= ALTER TABLE fullname(X) ADD CHECK(Y) LP(A) expr RP(B) onconf. { # TODO rewrite in Ruby }
kwcolumn_opt ::= .
kwcolumn_opt ::= COLUMNKW.
%endif SQLITE_OMIT_VIRTUALTABLE
%endif SQLITE_OMIT_ALTERTABLE
//////////////////////// CREATE VIRTUAL TABLE ... /////////////////////////////
%ifndef SQLITE_OMIT_VIRTUALTABLE
cmd ::= create_vtab. { # TODO rewrite in Ruby }
cmd ::= create_vtab LP vtabarglist RP(X). { # TODO rewrite in Ruby }
create_vtab ::= createkw VIRTUAL TABLE ifnotexists(E) nm(X) dbnm(Y) USING nm(Z). { # TODO rewrite in Ruby }
vtabarglist ::= vtabarg.
vtabarglist ::= vtabarglist COMMA vtabarg.
vtabarg ::= . { # TODO rewrite in Ruby }
vtabarg ::= vtabarg vtabargtoken.
vtabargtoken ::= ANY(X). { # TODO rewrite in Ruby }
vtabargtoken ::= lp anylist RP(X). { # TODO rewrite in Ruby }
lp ::= LP(X). { # TODO rewrite in Ruby }
anylist ::= .
anylist ::= anylist LP anylist RP.
anylist ::= anylist ANY.
%endif SQLITE_OMIT_VIRTUALTABLE
//////////////////////// COMMON TABLE EXPRESSIONS ////////////////////////////
%type wqlist {With*}
%type wqitem {Cte*}
// %destructor wqitem {sqlite3CteDelete(pParse->db, $$);} // not reachable
with ::= .
%ifndef SQLITE_OMIT_CTE
with ::= WITH wqlist(W). { # TODO rewrite in Ruby }
with ::= WITH RECURSIVE wqlist(W). { # TODO rewrite in Ruby }
%type wqas {u8}
wqas(A) ::= AS. { # TODO rewrite in Ruby }
wqas(A) ::= AS MATERIALIZED. { # TODO rewrite in Ruby }
wqas(A) ::= AS NOT MATERIALIZED. { # TODO rewrite in Ruby }
wqitem(A) ::= withnm(X) eidlist_opt(Y) wqas(M) LP select(Z) RP. { # TODO rewrite in Ruby }
withnm(A) ::= nm(A). { # TODO rewrite in Ruby }
wqlist(A) ::= wqitem(X). { # TODO rewrite in Ruby }
wqlist(A) ::= wqlist(A) COMMA wqitem(X). { # TODO rewrite in Ruby }
%endif SQLITE_OMIT_CTE
//////////////////////// WINDOW FUNCTION EXPRESSIONS /////////////////////////
// These must be at the end of this file. Specifically, the rules that
// introduce tokens WINDOW, OVER and FILTER must appear last. This causes 
// the integer values assigned to these tokens to be larger than all other 
// tokens that may be output by the tokenizer except TK_SPACE, TK_COMMENT,
// and TK_ILLEGAL.
//
%ifndef SQLITE_OMIT_WINDOWFUNC
%type windowdefn_list {Window*}
windowdefn_list(A) ::= windowdefn(A).
windowdefn_list(A) ::= windowdefn_list(Y) COMMA windowdefn(Z). { # TODO rewrite in Ruby }
%type windowdefn {Window*}
windowdefn(A) ::= nm(X) AS LP window(Y) RP. { # TODO rewrite in Ruby }
%type window {Window*}
%type frame_opt {Window*}
%type part_opt {ExprList*}
%type filter_clause {Expr*}
%type over_clause {Window*}
%type filter_over {Window*}
%type range_or_rows {int}
%type frame_bound {struct FrameBound}
%type frame_bound_s {struct FrameBound}
%type frame_bound_e {struct FrameBound}
window(A) ::= PARTITION BY nexprlist(X) orderby_opt(Y) frame_opt(Z). { # TODO rewrite in Ruby }
window(A) ::= nm(W) PARTITION BY nexprlist(X) orderby_opt(Y) frame_opt(Z). { # TODO rewrite in Ruby }
window(A) ::= ORDER BY sortlist(Y) frame_opt(Z). { # TODO rewrite in Ruby }
window(A) ::= nm(W) ORDER BY sortlist(Y) frame_opt(Z). { # TODO rewrite in Ruby }
window(A) ::= frame_opt(A).
window(A) ::= nm(W) frame_opt(Z). { # TODO rewrite in Ruby }
frame_opt(A) ::= . { # TODO rewrite in Ruby }
frame_opt(A) ::= range_or_rows(X) frame_bound_s(Y) frame_exclude_opt(Z). { # TODO rewrite in Ruby }
frame_opt(A) ::= range_or_rows(X) BETWEEN frame_bound_s(Y) AND frame_bound_e(Z) frame_exclude_opt(W). { # TODO rewrite in Ruby }
range_or_rows(A) ::= RANGE|ROWS|GROUPS(X). { # TODO rewrite in Ruby }
frame_bound_s(A) ::= frame_bound(X). { # TODO rewrite in Ruby }
frame_bound_s(A) ::= UNBOUNDED(X) PRECEDING. { # TODO rewrite in Ruby }
frame_bound_e(A) ::= frame_bound(X). { # TODO rewrite in Ruby }
frame_bound_e(A) ::= UNBOUNDED(X) FOLLOWING. { # TODO rewrite in Ruby }
frame_bound(A) ::= expr(X) PRECEDING|FOLLOWING(Y). { # TODO rewrite in Ruby }
frame_bound(A) ::= CURRENT(X) ROW. { # TODO rewrite in Ruby }
%type frame_exclude_opt {u8}
frame_exclude_opt(A) ::= . { # TODO rewrite in Ruby }
frame_exclude_opt(A) ::= EXCLUDE frame_exclude(X). { # TODO rewrite in Ruby }
%type frame_exclude {u8}
frame_exclude(A) ::= NO(X) OTHERS. { # TODO rewrite in Ruby }
frame_exclude(A) ::= CURRENT(X) ROW. { # TODO rewrite in Ruby }
frame_exclude(A) ::= GROUP|TIES(X). { # TODO rewrite in Ruby }
%type window_clause {Window*}
window_clause(A) ::= WINDOW windowdefn_list(B). { # TODO rewrite in Ruby }
filter_over(A) ::= filter_clause(F) over_clause(O). { # TODO rewrite in Ruby }
filter_over(A) ::= over_clause(O). { # TODO rewrite in Ruby }
filter_over(A) ::= filter_clause(F). { # TODO rewrite in Ruby }
over_clause(A) ::= OVER LP window(Z) RP. { # TODO rewrite in Ruby }
over_clause(A) ::= OVER nm(Z). { # TODO rewrite in Ruby }
filter_clause(A) ::= FILTER LP WHERE expr(X) RP. { # TODO rewrite in Ruby }
%endif
/* SQLITE_OMIT_WINDOWFUNC */
/*
** The code generator needs some extra TK_ token values for tokens that
** are synthesized and do not actually appear in the grammar:
*/
term(A) ::= QNUMBER(X). { # TODO rewrite in Ruby }
/* There must be no more than 255 tokens defined above.  If this grammar
** is extended with new rules and tokens, they must either be so few in
** number that TK_SPAN is no more than 255, or else the new tokens must
** appear after this line.
*/
// %include block stripped (contained C code)
/*
** The TK_SPACE, TK_COMMENT, and TK_ILLEGAL tokens must be the last three
** tokens.  The parser depends on this.  Those tokens are not used in any
** grammar rule.  They are only used by the tokenizer.  Declare them last
** so that they are guaranteed to be the last three.
*/
