CREATE TABLE t(id INTEGER PRIMARY KEY, a INTEGER, b TEXT, c REAL);
INSERT INTO t VALUES(1, 10, 'hello', 3.14);
INSERT INTO t VALUES(2, 20, NULL, NULL);
INSERT INTO t VALUES(3, NULL, 'world', 5.0);
INSERT INTO t VALUES(4, 30, 'hello', NULL);
INSERT INTO t VALUES(5, 10, NULL, 2.71);
